// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/models/shared"
	"net/http"
)

type AddAssignmentRequest struct {
	RoleID string `pathParam:"style=simple,explode=false,name=roleId"`
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

func (o *AddAssignmentRequest) GetRoleID() string {
	if o == nil {
		return ""
	}
	return o.RoleID
}

func (o *AddAssignmentRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type AddAssignmentResponse struct {
	// ok
	Assignment *shared.Assignment
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *AddAssignmentResponse) GetAssignment() *shared.Assignment {
	if o == nil {
		return nil
	}
	return o.Assignment
}

func (o *AddAssignmentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AddAssignmentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AddAssignmentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
