// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AssignRolesRequest struct {
	RequestBody []string `request:"mediaType=application/json"`
	UserID      string   `pathParam:"style=simple,explode=false,name=userId"`
}

func (o *AssignRolesRequest) GetRequestBody() []string {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *AssignRolesRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type AssignRolesResponse struct {
	// ok
	Assignments []string
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *AssignRolesResponse) GetAssignments() []string {
	if o == nil {
		return nil
	}
	return o.Assignments
}

func (o *AssignRolesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AssignRolesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AssignRolesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
