// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AssignRolesRequest struct {
	RequestBody []string `request:"mediaType=application/json"`
	UserID      string   `pathParam:"style=simple,explode=false,name=userId"`
}

func (a *AssignRolesRequest) GetRequestBody() []string {
	if a == nil {
		return nil
	}
	return a.RequestBody
}

func (a *AssignRolesRequest) GetUserID() string {
	if a == nil {
		return ""
	}
	return a.UserID
}

type AssignRolesResponse struct {
	// ok
	Assignments []string
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (a *AssignRolesResponse) GetAssignments() []string {
	if a == nil {
		return nil
	}
	return a.Assignments
}

func (a *AssignRolesResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AssignRolesResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AssignRolesResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}
