// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/models/shared"
	"net/http"
)

type CreateRoleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Invalid role configuration
	Error *shared.Error
	// ok
	Role *shared.Role
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateRoleResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateRoleResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *CreateRoleResponse) GetRole() *shared.Role {
	if c == nil {
		return nil
	}
	return c.Role
}

func (c *CreateRoleResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateRoleResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
