// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

type DeleteDashboardRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteDashboardRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteDashboardResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The deleted dashboard
	Dashboard *shared.Dashboard
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteDashboardResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteDashboardResponse) GetDashboard() *shared.Dashboard {
	if o == nil {
		return nil
	}
	return o.Dashboard
}

func (o *DeleteDashboardResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteDashboardResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
