// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAssignedRolesForUserRequest struct {
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

func (o *GetAssignedRolesForUserRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type GetAssignedRolesForUserResponse struct {
	// ok
	Assignments []string
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAssignedRolesForUserResponse) GetAssignments() []string {
	if o == nil {
		return nil
	}
	return o.Assignments
}

func (o *GetAssignedRolesForUserResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAssignedRolesForUserResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAssignedRolesForUserResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
