// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/models/shared"
	"net/http"
)

type GetRoleRequest struct {
	RoleID string `pathParam:"style=simple,explode=false,name=roleId"`
}

func (o *GetRoleRequest) GetRoleID() string {
	if o == nil {
		return ""
	}
	return o.RoleID
}

type GetRoleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// ok
	Role *shared.Role
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetRoleResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRoleResponse) GetRole() *shared.Role {
	if o == nil {
		return nil
	}
	return o.Role
}

func (o *GetRoleResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRoleResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
