// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

// ListAvailableVisualisationsResponseBody - List of available Visualisations to configure new dashboard tiles
type ListAvailableVisualisationsResponseBody struct {
	Results []shared.Visualisation `json:"results,omitempty"`
}

func (o *ListAvailableVisualisationsResponseBody) GetResults() []shared.Visualisation {
	if o == nil {
		return nil
	}
	return o.Results
}

type ListAvailableVisualisationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of available Visualisations to configure new dashboard tiles
	Object *ListAvailableVisualisationsResponseBody
}

func (o *ListAvailableVisualisationsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListAvailableVisualisationsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListAvailableVisualisationsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListAvailableVisualisationsResponse) GetObject() *ListAvailableVisualisationsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
