// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/models/shared"
	"net/http"
)

// ListCurrentRolesResponseBody - ok
type ListCurrentRolesResponseBody struct {
	Roles []shared.Role `json:"roles,omitempty"`
}

func (l *ListCurrentRolesResponseBody) GetRoles() []shared.Role {
	if l == nil {
		return nil
	}
	return l.Roles
}

type ListCurrentRolesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// ok
	Object *ListCurrentRolesResponseBody
}

func (l *ListCurrentRolesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListCurrentRolesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListCurrentRolesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListCurrentRolesResponse) GetObject() *ListCurrentRolesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
