// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/models/shared"
	"net/http"
)

// ListAllAssignmentsResponseBody - ok
type ListAllAssignmentsResponseBody struct {
	Assignments []shared.Assignment `json:"assignments,omitempty"`
}

func (l *ListAllAssignmentsResponseBody) GetAssignments() []shared.Assignment {
	if l == nil {
		return nil
	}
	return l.Assignments
}

type ListAllAssignmentsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// ok
	Object *ListAllAssignmentsResponseBody
}

func (l *ListAllAssignmentsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListAllAssignmentsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListAllAssignmentsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListAllAssignmentsResponse) GetObject() *ListAllAssignmentsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
