// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/models/shared"
	"net/http"
)

// ListAllAssignmentsResponseBody - ok
type ListAllAssignmentsResponseBody struct {
	Assignments []shared.Assignment `json:"assignments,omitempty"`
}

func (o *ListAllAssignmentsResponseBody) GetAssignments() []shared.Assignment {
	if o == nil {
		return nil
	}
	return o.Assignments
}

type ListAllAssignmentsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// ok
	Object *ListAllAssignmentsResponseBody
}

func (o *ListAllAssignmentsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListAllAssignmentsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListAllAssignmentsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListAllAssignmentsResponse) GetObject() *ListAllAssignmentsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
