// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

type PutDashboardRequest struct {
	// The updated dashboard
	Dashboard *shared.Dashboard `request:"mediaType=application/json"`
	ID        string            `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PutDashboardRequest) GetDashboard() *shared.Dashboard {
	if o == nil {
		return nil
	}
	return o.Dashboard
}

func (o *PutDashboardRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type PutDashboardResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The dashboard with the passed ID
	Dashboard *shared.Dashboard
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PutDashboardResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutDashboardResponse) GetDashboard() *shared.Dashboard {
	if o == nil {
		return nil
	}
	return o.Dashboard
}

func (o *PutDashboardResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutDashboardResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
