// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/models/shared"
	"net/http"
)

type PutRoleRequest struct {
	RolePayload *shared.RolePayload `request:"mediaType=application/json"`
	RoleID      string              `pathParam:"style=simple,explode=false,name=roleId"`
}

func (p *PutRoleRequest) GetRolePayload() *shared.RolePayload {
	if p == nil {
		return nil
	}
	return p.RolePayload
}

func (p *PutRoleRequest) GetRoleID() string {
	if p == nil {
		return ""
	}
	return p.RoleID
}

type PutRoleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Bad Request - Invalid role configuration
	Error *shared.Error
	// ok
	Role *shared.Role
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PutRoleResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutRoleResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PutRoleResponse) GetRole() *shared.Role {
	if p == nil {
		return nil
	}
	return p.Role
}

func (p *PutRoleResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutRoleResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}
