// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/models/shared"
	"net/http"
)

type RemoveAssignmentRequest struct {
	RoleID string `pathParam:"style=simple,explode=false,name=roleId"`
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

func (r *RemoveAssignmentRequest) GetRoleID() string {
	if r == nil {
		return ""
	}
	return r.RoleID
}

func (r *RemoveAssignmentRequest) GetUserID() string {
	if r == nil {
		return ""
	}
	return r.UserID
}

type RemoveAssignmentResponse struct {
	// ok
	Assignment *shared.Assignment
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *RemoveAssignmentResponse) GetAssignment() *shared.Assignment {
	if r == nil {
		return nil
	}
	return r.Assignment
}

func (r *RemoveAssignmentResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RemoveAssignmentResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RemoveAssignmentResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
