// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/models/shared"
	"net/http"
)

// SearchRolesResponseBody - ok
type SearchRolesResponseBody struct {
	Hits    *float64      `json:"hits,omitempty"`
	Results []shared.Role `json:"results,omitempty"`
}

func (o *SearchRolesResponseBody) GetHits() *float64 {
	if o == nil {
		return nil
	}
	return o.Hits
}

func (o *SearchRolesResponseBody) GetResults() []shared.Role {
	if o == nil {
		return nil
	}
	return o.Results
}

type SearchRolesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// ok
	Object *SearchRolesResponseBody
}

func (o *SearchRolesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SearchRolesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SearchRolesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *SearchRolesResponse) GetObject() *SearchRolesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
