// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Assignment - A role attached to an user
type Assignment struct {
	Roles []string `json:"roles,omitempty"`
	// Id of a user
	UserID *string `json:"user_id,omitempty"`
}

func (o *Assignment) GetRoles() []string {
	if o == nil {
		return nil
	}
	return o.Roles
}

func (o *Assignment) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}
