// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/internal/utils"
)

type DatalakeQuery struct {
	AdditionalProperties any              `additionalProperties:"true" json:"-"`
	Dataset              *string          `json:"dataset,omitempty"`
	Dimensions           []map[string]any `json:"dimensions,omitempty"`
	Filters              []map[string]any `json:"filters,omitempty"`
	Measure              *string          `json:"measure,omitempty"`
}

func (d DatalakeQuery) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DatalakeQuery) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DatalakeQuery) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *DatalakeQuery) GetDataset() *string {
	if o == nil {
		return nil
	}
	return o.Dataset
}

func (o *DatalakeQuery) GetDimensions() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Dimensions
}

func (o *DatalakeQuery) GetFilters() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Filters
}

func (o *DatalakeQuery) GetMeasure() *string {
	if o == nil {
		return nil
	}
	return o.Measure
}
