// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Operation string

const (
	OperationEquals Operation = "equals"
)

func (e Operation) ToPointer() *Operation {
	return &e
}
func (e *Operation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "equals":
		*e = Operation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Operation: %v", v)
	}
}

// EqualsCondition - Check if attribute equals to any of the values
type EqualsCondition struct {
	Attribute string    `json:"attribute"`
	Operation Operation `json:"operation"`
	Values    []any     `json:"values"`
}

func (o *EqualsCondition) GetAttribute() string {
	if o == nil {
		return ""
	}
	return o.Attribute
}

func (o *EqualsCondition) GetOperation() Operation {
	if o == nil {
		return Operation("")
	}
	return o.Operation
}

func (o *EqualsCondition) GetValues() []any {
	if o == nil {
		return []any{}
	}
	return o.Values
}
