// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/internal/utils"
)

type EqualsCurrentUserConditionOperation string

const (
	EqualsCurrentUserConditionOperationEqualsCurrentUser EqualsCurrentUserConditionOperation = "equals_current_user"
)

func (e EqualsCurrentUserConditionOperation) ToPointer() *EqualsCurrentUserConditionOperation {
	return &e
}
func (e *EqualsCurrentUserConditionOperation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "equals_current_user":
		*e = EqualsCurrentUserConditionOperation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EqualsCurrentUserConditionOperation: %v", v)
	}
}

// EqualsCurrentUserCondition - Check if any relation_user attribute on the entity contains the current user. When attribute is provided, only that specific attribute path is checked.
type EqualsCurrentUserCondition struct {
	// Optional JSON path to a specific user attribute. When omitted, all relation_user attributes on the entity are scanned.
	Attribute *string                             `json:"attribute,omitempty"`
	Operation EqualsCurrentUserConditionOperation `json:"operation"`
}

func (e EqualsCurrentUserCondition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EqualsCurrentUserCondition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EqualsCurrentUserCondition) GetAttribute() *string {
	if e == nil {
		return nil
	}
	return e.Attribute
}

func (e *EqualsCurrentUserCondition) GetOperation() EqualsCurrentUserConditionOperation {
	if e == nil {
		return EqualsCurrentUserConditionOperation("")
	}
	return e.Operation
}
