// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Error response
type Error struct {
	// Error message
	Message string `json:"message"`
}

func (e *Error) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}
