// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Example struct {
	// Unique identifier for a visualisation examples for tiles in a dashboard
	ID    *string        `json:"id,omitempty"`
	Query *DatalakeQuery `json:"query,omitempty"`
	Title *string        `json:"title,omitempty"`
	// Unique identifier for a Visualisation
	Visualisation *VisualisationID `json:"visualisation,omitempty"`
}

func (o *Example) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Example) GetQuery() *DatalakeQuery {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *Example) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *Example) GetVisualisation() *VisualisationID {
	if o == nil {
		return nil
	}
	return o.Visualisation
}
