// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/internal/utils"
)

type GrantWithDependenciesEffect string

const (
	GrantWithDependenciesEffectAllow GrantWithDependenciesEffect = "allow"
	GrantWithDependenciesEffectDeny  GrantWithDependenciesEffect = "deny"
)

func (e GrantWithDependenciesEffect) ToPointer() *GrantWithDependenciesEffect {
	return &e
}
func (e *GrantWithDependenciesEffect) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "allow":
		fallthrough
	case "deny":
		*e = GrantWithDependenciesEffect(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GrantWithDependenciesEffect: %v", v)
	}
}

type GrantWithDependencies struct {
	Action     string           `json:"action"`
	Conditions []GrantCondition `json:"conditions,omitempty"`
	// Provided additional dependencies, exploded when storing the role
	Dependencies []Grant                      `json:"dependencies,omitempty"`
	Effect       *GrantWithDependenciesEffect `default:"allow" json:"effect"`
	Resource     *string                      `json:"resource,omitempty"`
}

func (g GrantWithDependencies) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GrantWithDependencies) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GrantWithDependencies) GetAction() string {
	if o == nil {
		return ""
	}
	return o.Action
}

func (o *GrantWithDependencies) GetConditions() []GrantCondition {
	if o == nil {
		return nil
	}
	return o.Conditions
}

func (o *GrantWithDependencies) GetDependencies() []Grant {
	if o == nil {
		return nil
	}
	return o.Dependencies
}

func (o *GrantWithDependencies) GetEffect() *GrantWithDependenciesEffect {
	if o == nil {
		return nil
	}
	return o.Effect
}

func (o *GrantWithDependencies) GetResource() *string {
	if o == nil {
		return nil
	}
	return o.Resource
}
