// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// InternalAssignment - A role attached to an user
type InternalAssignment struct {
	Roles []string `json:"roles,omitempty"`
	// Id of a user
	UserID *string `json:"userId,omitempty"`
}

func (o *InternalAssignment) GetRoles() []string {
	if o == nil {
		return nil
	}
	return o.Roles
}

func (o *InternalAssignment) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}
