// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// OrgAssignments - All roles attached to an users of an organization
type OrgAssignments struct {
	Assignments []InternalAssignment `json:"assignments,omitempty"`
	// Id of an organization
	OrganizationID *string `json:"organizationId,omitempty"`
}

func (o *OrgAssignments) GetAssignments() []InternalAssignment {
	if o == nil {
		return nil
	}
	return o.Assignments
}

func (o *OrgAssignments) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}
