// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// OrgRoles - All roles attached to an users of an organization
type OrgRoles struct {
	// Id of an organization
	OrganizationID *string `json:"organizationId,omitempty"`
	Roles          []Role  `json:"roles,omitempty"`
}

func (o *OrgRoles) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *OrgRoles) GetRoles() []Role {
	if o == nil {
		return nil
	}
	return o.Roles
}
