// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk/internal/utils"
)

type RoleSearchInput struct {
	// The Number of roles to return
	Limit *float64 `default:"50" json:"limit"`
	// The number of roles to skip before starting to collect the result set
	Offset *float64 `default:"0" json:"offset"`
	// List of organization ids to filter by
	OrgIds []string `json:"org_ids,omitempty"`
	// Input to search across fields
	Query *string `json:"query,omitempty"`
	// List of role ids to filter by
	RoleIds []string `json:"role_ids,omitempty"`
	// List of role slugs to filter by
	Slugs []string `json:"slugs,omitempty"`
}

func (r RoleSearchInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RoleSearchInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RoleSearchInput) GetLimit() *float64 {
	if r == nil {
		return nil
	}
	return r.Limit
}

func (r *RoleSearchInput) GetOffset() *float64 {
	if r == nil {
		return nil
	}
	return r.Offset
}

func (r *RoleSearchInput) GetOrgIds() []string {
	if r == nil {
		return nil
	}
	return r.OrgIds
}

func (r *RoleSearchInput) GetQuery() *string {
	if r == nil {
		return nil
	}
	return r.Query
}

func (r *RoleSearchInput) GetRoleIds() []string {
	if r == nil {
		return nil
	}
	return r.RoleIds
}

func (r *RoleSearchInput) GetSlugs() []string {
	if r == nil {
		return nil
	}
	return r.Slugs
}
