// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// A Visualisation that can be used to configure tiles in dashboards
type Visualisation struct {
	Description *string `json:"description,omitempty"`
	// URL to Visualisation MFE bundle to import
	ImportURL *string `json:"import_url,omitempty"`
	// Package name of the Visualisation MFE bundle to import
	PackageName *string `json:"package_name,omitempty"`
	Title       *string `json:"title,omitempty"`
	// Unique identifier for a Visualisation
	Visualisation *VisualisationID `json:"visualisation,omitempty"`
}

func (o *Visualisation) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Visualisation) GetImportURL() *string {
	if o == nil {
		return nil
	}
	return o.ImportURL
}

func (o *Visualisation) GetPackageName() *string {
	if o == nil {
		return nil
	}
	return o.PackageName
}

func (o *Visualisation) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *Visualisation) GetVisualisation() *VisualisationID {
	if o == nil {
		return nil
	}
	return o.Visualisation
}
