// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *DashboardResourceModel) ToSharedDashboard() *shared.Dashboard {
	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	var tiles interface{}
	_ = json.Unmarshal([]byte(r.Tiles.ValueString()), &tiles)
	var title string
	title = r.Title.ValueString()

	out := shared.Dashboard{
		ID:    id,
		Tiles: tiles,
		Title: title,
	}
	return &out
}

func (r *DashboardResourceModel) RefreshFromSharedDashboard(resp *shared.Dashboard) {
	if resp != nil {
		r.ID = types.StringPointerValue(resp.ID)
		tilesResult, _ := json.Marshal(resp.Tiles)
		r.Tiles = types.StringValue(string(tilesResult))
		r.Title = types.StringValue(resp.Title)
	}
}
