// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-role/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/sdk"
	"github.com/epilot-dev/terraform-provider-epilot-role/internal/validators"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &RoleResource{}
var _ resource.ResourceWithImportState = &RoleResource{}

func NewRoleResource() resource.Resource {
	return &RoleResource{}
}

// RoleResource defines the resource implementation.
type RoleResource struct {
	client *sdk.SDK
}

// RoleResourceModel describes the resource data model.
type RoleResourceModel struct {
	Five           *tfTypes.Five    `queryParam:"inline" tfsdk:"five" tfPlanOnly:"true"`
	Four           *tfTypes.Four    `queryParam:"inline" tfsdk:"four" tfPlanOnly:"true"`
	ID             types.String     `tfsdk:"id"`
	Name           types.String     `tfsdk:"name"`
	One            *tfTypes.Five    `queryParam:"inline" tfsdk:"one" tfPlanOnly:"true"`
	OrganizationID types.String     `tfsdk:"organization_id"`
	Schemas        *tfTypes.Schemas `queryParam:"inline" tfsdk:"schemas" tfPlanOnly:"true"`
	Slug           types.String     `tfsdk:"slug"`
	Three          *tfTypes.Five    `queryParam:"inline" tfsdk:"three" tfPlanOnly:"true"`
	Two            *tfTypes.Two     `queryParam:"inline" tfsdk:"two" tfPlanOnly:"true"`
}

func (r *RoleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_role"
}

func (r *RoleResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Role Resource",
		Attributes: map[string]schema.Attribute{
			"five": schema.SingleNestedAttribute{
				Optional: true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplaceIfConfigured(),
				},
				Attributes: map[string]schema.Attribute{
					"expires_at": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `date and time then the role will expire. Requires replacement if changed.`,
						Validators: []validator.String{
							validators.IsRFC3339(),
						},
					},
					"grants": schema.ListNestedAttribute{
						Required: true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.RequiresReplaceIfConfigured(),
						},
						NestedObject: schema.NestedAttributeObject{
							PlanModifiers: []planmodifier.Object{
								objectplanmodifier.RequiresReplaceIfConfigured(),
							},
							Attributes: map[string]schema.Attribute{
								"action": schema.StringAttribute{
									Required: true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Requires replacement if changed.`,
								},
								"conditions": schema.ListNestedAttribute{
									Optional: true,
									PlanModifiers: []planmodifier.List{
										listplanmodifier.RequiresReplaceIfConfigured(),
									},
									NestedObject: schema.NestedAttributeObject{
										PlanModifiers: []planmodifier.Object{
											objectplanmodifier.RequiresReplaceIfConfigured(),
										},
										Attributes: map[string]schema.Attribute{
											"equals_condition": schema.SingleNestedAttribute{
												Optional: true,
												PlanModifiers: []planmodifier.Object{
													objectplanmodifier.RequiresReplaceIfConfigured(),
												},
												Attributes: map[string]schema.Attribute{
													"attribute": schema.StringAttribute{
														Required: true,
														PlanModifiers: []planmodifier.String{
															stringplanmodifier.RequiresReplaceIfConfigured(),
														},
														Description: `Requires replacement if changed.`,
													},
													"operation": schema.StringAttribute{
														Required: true,
														PlanModifiers: []planmodifier.String{
															stringplanmodifier.RequiresReplaceIfConfigured(),
														},
														Description: `must be "equals"; Requires replacement if changed.`,
														Validators: []validator.String{
															stringvalidator.OneOf("equals"),
														},
													},
													"values": schema.ListAttribute{
														Required: true,
														PlanModifiers: []planmodifier.List{
															listplanmodifier.RequiresReplaceIfConfigured(),
														},
														ElementType: types.StringType,
														Description: `Requires replacement if changed.`,
														Validators: []validator.List{
															listvalidator.ValueStringsAre(validators.IsValidJSON()),
														},
													},
												},
												Description: `Check if attribute equals to any of the values. Requires replacement if changed.`,
											},
										},
									},
									Description: `Requires replacement if changed.`,
								},
								"effect": schema.StringAttribute{
									Computed: true,
									Optional: true,
									Default:  stringdefault.StaticString(`allow`),
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Default: "allow"; must be one of ["allow", "deny"]; Requires replacement if changed.`,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"allow",
											"deny",
										),
									},
								},
								"resource": schema.StringAttribute{
									Optional: true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Requires replacement if changed.`,
								},
							},
						},
						Description: `List of grants (permissions) applied to the role. Requires replacement if changed.`,
					},
					"id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Format: <organization_id>:<slug>. Requires replacement if changed.`,
					},
					"name": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Human-friendly name for the role. Requires replacement if changed.`,
					},
					"organization_id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Id of an organization. Requires replacement if changed.`,
					},
					"slug": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `URL-friendly name for the role. Requires replacement if changed.`,
					},
					"type": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Type of the role. Requires replacement if changed.`,
					},
				},
				Description: `A role that is applied to end customers and installers using the Portals. Requires replacement if changed.`,
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{
						path.MatchRelative().AtParent().AtName("one"),
						path.MatchRelative().AtParent().AtName("two"),
						path.MatchRelative().AtParent().AtName("three"),
						path.MatchRelative().AtParent().AtName("four"),
						path.MatchRelative().AtParent().AtName("schemas"),
					}...),
				},
			},
			"four": schema.SingleNestedAttribute{
				Optional: true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplaceIfConfigured(),
				},
				Attributes: map[string]schema.Attribute{
					"expires_at": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `date and time then the role will expire. Requires replacement if changed.`,
						Validators: []validator.String{
							validators.IsRFC3339(),
						},
					},
					"grants": schema.ListNestedAttribute{
						Required: true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.RequiresReplaceIfConfigured(),
						},
						NestedObject: schema.NestedAttributeObject{
							PlanModifiers: []planmodifier.Object{
								objectplanmodifier.RequiresReplaceIfConfigured(),
							},
							Attributes: map[string]schema.Attribute{
								"action": schema.StringAttribute{
									Required: true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Requires replacement if changed.`,
								},
								"conditions": schema.ListNestedAttribute{
									Optional: true,
									PlanModifiers: []planmodifier.List{
										listplanmodifier.RequiresReplaceIfConfigured(),
									},
									NestedObject: schema.NestedAttributeObject{
										PlanModifiers: []planmodifier.Object{
											objectplanmodifier.RequiresReplaceIfConfigured(),
										},
										Attributes: map[string]schema.Attribute{
											"equals_condition": schema.SingleNestedAttribute{
												Optional: true,
												PlanModifiers: []planmodifier.Object{
													objectplanmodifier.RequiresReplaceIfConfigured(),
												},
												Attributes: map[string]schema.Attribute{
													"attribute": schema.StringAttribute{
														Required: true,
														PlanModifiers: []planmodifier.String{
															stringplanmodifier.RequiresReplaceIfConfigured(),
														},
														Description: `Requires replacement if changed.`,
													},
													"operation": schema.StringAttribute{
														Required: true,
														PlanModifiers: []planmodifier.String{
															stringplanmodifier.RequiresReplaceIfConfigured(),
														},
														Description: `must be "equals"; Requires replacement if changed.`,
														Validators: []validator.String{
															stringvalidator.OneOf("equals"),
														},
													},
													"values": schema.ListAttribute{
														Required: true,
														PlanModifiers: []planmodifier.List{
															listplanmodifier.RequiresReplaceIfConfigured(),
														},
														ElementType: types.StringType,
														Description: `Requires replacement if changed.`,
														Validators: []validator.List{
															listvalidator.ValueStringsAre(validators.IsValidJSON()),
														},
													},
												},
												Description: `Check if attribute equals to any of the values. Requires replacement if changed.`,
											},
										},
									},
									Description: `Requires replacement if changed.`,
								},
								"effect": schema.StringAttribute{
									Computed: true,
									Optional: true,
									Default:  stringdefault.StaticString(`allow`),
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Default: "allow"; must be one of ["allow", "deny"]; Requires replacement if changed.`,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"allow",
											"deny",
										),
									},
								},
								"resource": schema.StringAttribute{
									Optional: true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Requires replacement if changed.`,
								},
							},
						},
						Description: `List of grants (permissions) applied to the role. Requires replacement if changed.`,
					},
					"id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Format: <organization_id>:<slug>. Requires replacement if changed.`,
					},
					"name": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Human-friendly name for the role. Requires replacement if changed.`,
					},
					"organization_id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Id of an organization. Requires replacement if changed.`,
					},
					"partner_org_id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Requires replacement if changed.`,
					},
					"slug": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `URL-friendly name for the role. Requires replacement if changed.`,
					},
					"type": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Type of the role. Requires replacement if changed.`,
					},
				},
				Description: `A role that appears in another organization's role list that can be assigned but not modified by the partner organization. Requires replacement if changed.`,
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{
						path.MatchRelative().AtParent().AtName("one"),
						path.MatchRelative().AtParent().AtName("two"),
						path.MatchRelative().AtParent().AtName("three"),
						path.MatchRelative().AtParent().AtName("five"),
						path.MatchRelative().AtParent().AtName("schemas"),
					}...),
				},
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: `Format: <organization_id>:<slug>`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Human-friendly name for the role`,
			},
			"one": schema.SingleNestedAttribute{
				Optional: true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplaceIfConfigured(),
				},
				Attributes: map[string]schema.Attribute{
					"expires_at": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `date and time then the role will expire. Requires replacement if changed.`,
						Validators: []validator.String{
							validators.IsRFC3339(),
						},
					},
					"grants": schema.ListNestedAttribute{
						Required: true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.RequiresReplaceIfConfigured(),
						},
						NestedObject: schema.NestedAttributeObject{
							PlanModifiers: []planmodifier.Object{
								objectplanmodifier.RequiresReplaceIfConfigured(),
							},
							Attributes: map[string]schema.Attribute{
								"action": schema.StringAttribute{
									Required: true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Requires replacement if changed.`,
								},
								"conditions": schema.ListNestedAttribute{
									Optional: true,
									PlanModifiers: []planmodifier.List{
										listplanmodifier.RequiresReplaceIfConfigured(),
									},
									NestedObject: schema.NestedAttributeObject{
										PlanModifiers: []planmodifier.Object{
											objectplanmodifier.RequiresReplaceIfConfigured(),
										},
										Attributes: map[string]schema.Attribute{
											"equals_condition": schema.SingleNestedAttribute{
												Optional: true,
												PlanModifiers: []planmodifier.Object{
													objectplanmodifier.RequiresReplaceIfConfigured(),
												},
												Attributes: map[string]schema.Attribute{
													"attribute": schema.StringAttribute{
														Required: true,
														PlanModifiers: []planmodifier.String{
															stringplanmodifier.RequiresReplaceIfConfigured(),
														},
														Description: `Requires replacement if changed.`,
													},
													"operation": schema.StringAttribute{
														Required: true,
														PlanModifiers: []planmodifier.String{
															stringplanmodifier.RequiresReplaceIfConfigured(),
														},
														Description: `must be "equals"; Requires replacement if changed.`,
														Validators: []validator.String{
															stringvalidator.OneOf("equals"),
														},
													},
													"values": schema.ListAttribute{
														Required: true,
														PlanModifiers: []planmodifier.List{
															listplanmodifier.RequiresReplaceIfConfigured(),
														},
														ElementType: types.StringType,
														Description: `Requires replacement if changed.`,
														Validators: []validator.List{
															listvalidator.ValueStringsAre(validators.IsValidJSON()),
														},
													},
												},
												Description: `Check if attribute equals to any of the values. Requires replacement if changed.`,
											},
										},
									},
									Description: `Requires replacement if changed.`,
								},
								"effect": schema.StringAttribute{
									Computed: true,
									Optional: true,
									Default:  stringdefault.StaticString(`allow`),
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Default: "allow"; must be one of ["allow", "deny"]; Requires replacement if changed.`,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"allow",
											"deny",
										),
									},
								},
								"resource": schema.StringAttribute{
									Optional: true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Requires replacement if changed.`,
								},
							},
						},
						Description: `List of grants (permissions) applied to the role. Requires replacement if changed.`,
					},
					"id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Format: <organization_id>:<slug>. Requires replacement if changed.`,
					},
					"name": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Human-friendly name for the role. Requires replacement if changed.`,
					},
					"organization_id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Id of an organization. Requires replacement if changed.`,
					},
					"slug": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `URL-friendly name for the role. Requires replacement if changed.`,
					},
					"type": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Type of the role. Requires replacement if changed.`,
					},
				},
				Description: `A standard user role. Must be explicitly assigned to users. Requires replacement if changed.`,
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{
						path.MatchRelative().AtParent().AtName("two"),
						path.MatchRelative().AtParent().AtName("three"),
						path.MatchRelative().AtParent().AtName("four"),
						path.MatchRelative().AtParent().AtName("five"),
						path.MatchRelative().AtParent().AtName("schemas"),
					}...),
				},
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Description: `Id of an organization`,
			},
			"schemas": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"expires_at": schema.StringAttribute{
						Computed:    true,
						Description: `date and time then the role will expire`,
						Validators: []validator.String{
							validators.IsRFC3339(),
						},
					},
					"grants": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"action": schema.StringAttribute{
									Computed: true,
								},
								"conditions": schema.ListNestedAttribute{
									Computed: true,
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"equals_condition": schema.SingleNestedAttribute{
												Computed: true,
												Attributes: map[string]schema.Attribute{
													"attribute": schema.StringAttribute{
														Computed: true,
													},
													"operation": schema.StringAttribute{
														Computed:    true,
														Description: `must be "equals"`,
														Validators: []validator.String{
															stringvalidator.OneOf("equals"),
														},
													},
													"values": schema.ListAttribute{
														Computed:    true,
														ElementType: types.StringType,
														Validators: []validator.List{
															listvalidator.ValueStringsAre(validators.IsValidJSON()),
														},
													},
												},
												Description: `Check if attribute equals to any of the values`,
											},
										},
									},
								},
								"effect": schema.StringAttribute{
									Computed:    true,
									Default:     stringdefault.StaticString(`allow`),
									Description: `Default: "allow"; must be one of ["allow", "deny"]`,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"allow",
											"deny",
										),
									},
								},
								"resource": schema.StringAttribute{
									Computed: true,
								},
							},
						},
						Description: `List of grants (permissions) applied to the role`,
					},
					"id": schema.StringAttribute{
						Computed:    true,
						Description: `Format: <organization_id>:<slug>`,
					},
					"name": schema.StringAttribute{
						Computed:    true,
						Description: `Human-friendly name for the role`,
					},
					"organization_id": schema.StringAttribute{
						Computed:    true,
						Description: `Id of an organization`,
					},
					"partner_org_id": schema.StringAttribute{
						Computed: true,
					},
					"pricing_tier": schema.StringAttribute{
						Computed:    true,
						Description: `The pricing tier of the organization this root role is based on`,
					},
					"slug": schema.StringAttribute{
						Computed:    true,
						Description: `URL-friendly name for the role`,
					},
					"type": schema.StringAttribute{
						Computed:    true,
						Description: `must be "user_role"`,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"user_role",
							),
						},
					},
				},
				Description: `A role that is applied to end customers and installers using the Portals`,
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{
						path.MatchRelative().AtParent().AtName("one"),
						path.MatchRelative().AtParent().AtName("two"),
						path.MatchRelative().AtParent().AtName("three"),
						path.MatchRelative().AtParent().AtName("four"),
						path.MatchRelative().AtParent().AtName("five"),
					}...),
				},
			},
			"slug": schema.StringAttribute{
				Computed:    true,
				Description: `URL-friendly name for the role`,
			},
			"three": schema.SingleNestedAttribute{
				Optional: true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplaceIfConfigured(),
				},
				Attributes: map[string]schema.Attribute{
					"expires_at": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `date and time then the role will expire. Requires replacement if changed.`,
						Validators: []validator.String{
							validators.IsRFC3339(),
						},
					},
					"grants": schema.ListNestedAttribute{
						Required: true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.RequiresReplaceIfConfigured(),
						},
						NestedObject: schema.NestedAttributeObject{
							PlanModifiers: []planmodifier.Object{
								objectplanmodifier.RequiresReplaceIfConfigured(),
							},
							Attributes: map[string]schema.Attribute{
								"action": schema.StringAttribute{
									Required: true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Requires replacement if changed.`,
								},
								"conditions": schema.ListNestedAttribute{
									Optional: true,
									PlanModifiers: []planmodifier.List{
										listplanmodifier.RequiresReplaceIfConfigured(),
									},
									NestedObject: schema.NestedAttributeObject{
										PlanModifiers: []planmodifier.Object{
											objectplanmodifier.RequiresReplaceIfConfigured(),
										},
										Attributes: map[string]schema.Attribute{
											"equals_condition": schema.SingleNestedAttribute{
												Optional: true,
												PlanModifiers: []planmodifier.Object{
													objectplanmodifier.RequiresReplaceIfConfigured(),
												},
												Attributes: map[string]schema.Attribute{
													"attribute": schema.StringAttribute{
														Required: true,
														PlanModifiers: []planmodifier.String{
															stringplanmodifier.RequiresReplaceIfConfigured(),
														},
														Description: `Requires replacement if changed.`,
													},
													"operation": schema.StringAttribute{
														Required: true,
														PlanModifiers: []planmodifier.String{
															stringplanmodifier.RequiresReplaceIfConfigured(),
														},
														Description: `must be "equals"; Requires replacement if changed.`,
														Validators: []validator.String{
															stringvalidator.OneOf("equals"),
														},
													},
													"values": schema.ListAttribute{
														Required: true,
														PlanModifiers: []planmodifier.List{
															listplanmodifier.RequiresReplaceIfConfigured(),
														},
														ElementType: types.StringType,
														Description: `Requires replacement if changed.`,
														Validators: []validator.List{
															listvalidator.ValueStringsAre(validators.IsValidJSON()),
														},
													},
												},
												Description: `Check if attribute equals to any of the values. Requires replacement if changed.`,
											},
										},
									},
									Description: `Requires replacement if changed.`,
								},
								"effect": schema.StringAttribute{
									Computed: true,
									Optional: true,
									Default:  stringdefault.StaticString(`allow`),
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Default: "allow"; must be one of ["allow", "deny"]; Requires replacement if changed.`,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"allow",
											"deny",
										),
									},
								},
								"resource": schema.StringAttribute{
									Optional: true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Requires replacement if changed.`,
								},
							},
						},
						Description: `List of grants (permissions) applied to the role. Requires replacement if changed.`,
					},
					"id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Format: <organization_id>:<slug>. Requires replacement if changed.`,
					},
					"name": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Human-friendly name for the role. Requires replacement if changed.`,
					},
					"organization_id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Id of an organization. Requires replacement if changed.`,
					},
					"slug": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `URL-friendly name for the role. Requires replacement if changed.`,
					},
					"type": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Type of the role. Requires replacement if changed.`,
					},
				},
				Description: `A role that can be assigned to users in other organizations for sharing purposes. Requires replacement if changed.`,
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{
						path.MatchRelative().AtParent().AtName("one"),
						path.MatchRelative().AtParent().AtName("two"),
						path.MatchRelative().AtParent().AtName("four"),
						path.MatchRelative().AtParent().AtName("five"),
						path.MatchRelative().AtParent().AtName("schemas"),
					}...),
				},
			},
			"two": schema.SingleNestedAttribute{
				Optional: true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplaceIfConfigured(),
				},
				Attributes: map[string]schema.Attribute{
					"expires_at": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `date and time then the role will expire. Requires replacement if changed.`,
						Validators: []validator.String{
							validators.IsRFC3339(),
						},
					},
					"grants": schema.ListNestedAttribute{
						Required: true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.RequiresReplaceIfConfigured(),
						},
						NestedObject: schema.NestedAttributeObject{
							PlanModifiers: []planmodifier.Object{
								objectplanmodifier.RequiresReplaceIfConfigured(),
							},
							Attributes: map[string]schema.Attribute{
								"action": schema.StringAttribute{
									Required: true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Requires replacement if changed.`,
								},
								"conditions": schema.ListNestedAttribute{
									Optional: true,
									PlanModifiers: []planmodifier.List{
										listplanmodifier.RequiresReplaceIfConfigured(),
									},
									NestedObject: schema.NestedAttributeObject{
										PlanModifiers: []planmodifier.Object{
											objectplanmodifier.RequiresReplaceIfConfigured(),
										},
										Attributes: map[string]schema.Attribute{
											"equals_condition": schema.SingleNestedAttribute{
												Optional: true,
												PlanModifiers: []planmodifier.Object{
													objectplanmodifier.RequiresReplaceIfConfigured(),
												},
												Attributes: map[string]schema.Attribute{
													"attribute": schema.StringAttribute{
														Required: true,
														PlanModifiers: []planmodifier.String{
															stringplanmodifier.RequiresReplaceIfConfigured(),
														},
														Description: `Requires replacement if changed.`,
													},
													"operation": schema.StringAttribute{
														Required: true,
														PlanModifiers: []planmodifier.String{
															stringplanmodifier.RequiresReplaceIfConfigured(),
														},
														Description: `must be "equals"; Requires replacement if changed.`,
														Validators: []validator.String{
															stringvalidator.OneOf("equals"),
														},
													},
													"values": schema.ListAttribute{
														Required: true,
														PlanModifiers: []planmodifier.List{
															listplanmodifier.RequiresReplaceIfConfigured(),
														},
														ElementType: types.StringType,
														Description: `Requires replacement if changed.`,
														Validators: []validator.List{
															listvalidator.ValueStringsAre(validators.IsValidJSON()),
														},
													},
												},
												Description: `Check if attribute equals to any of the values. Requires replacement if changed.`,
											},
										},
									},
									Description: `Requires replacement if changed.`,
								},
								"effect": schema.StringAttribute{
									Computed: true,
									Optional: true,
									Default:  stringdefault.StaticString(`allow`),
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Default: "allow"; must be one of ["allow", "deny"]; Requires replacement if changed.`,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"allow",
											"deny",
										),
									},
								},
								"resource": schema.StringAttribute{
									Optional: true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.RequiresReplaceIfConfigured(),
									},
									Description: `Requires replacement if changed.`,
								},
							},
						},
						Description: `List of grants (permissions) applied to the role. Requires replacement if changed.`,
					},
					"id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Format: <organization_id>:<slug>. Requires replacement if changed.`,
					},
					"name": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Human-friendly name for the role. Requires replacement if changed.`,
					},
					"organization_id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Id of an organization. Requires replacement if changed.`,
					},
					"pricing_tier": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `The pricing tier of the organization this root role is based on. Requires replacement if changed.`,
					},
					"slug": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `URL-friendly name for the role. Requires replacement if changed.`,
					},
					"type": schema.StringAttribute{
						Required: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `Type of the role. Requires replacement if changed.`,
					},
				},
				Description: `A role automatically applied to all users in an organization. Requires replacement if changed.`,
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{
						path.MatchRelative().AtParent().AtName("one"),
						path.MatchRelative().AtParent().AtName("three"),
						path.MatchRelative().AtParent().AtName("four"),
						path.MatchRelative().AtParent().AtName("five"),
						path.MatchRelative().AtParent().AtName("schemas"),
					}...),
				},
			},
		},
	}
}

func (r *RoleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *RoleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *RoleResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToSharedCreateRolePayload(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Roles.CreateRole(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Role != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedRole(ctx, res.Role)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RoleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *RoleResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetRoleRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Roles.GetRole(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Role != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedRole(ctx, res.Role)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RoleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *RoleResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsPutRoleRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Roles.PutRole(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Role != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedRole(ctx, res.Role)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}
	request1, request1Diags := data.ToOperationsGetRoleRequest(ctx)
	resp.Diagnostics.Append(request1Diags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res1, err := r.client.Roles.GetRole(ctx, *request1)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res1 != nil && res1.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res1.RawResponse))
		}
		return
	}
	if res1 == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res1))
		return
	}
	if res1.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res1.StatusCode), debugResponse(res1.RawResponse))
		return
	}
	if !(res1.Role != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res1.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedRole(ctx, res1.Role)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RoleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *RoleResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsDeleteRoleRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Roles.DeleteRole(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *RoleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
