// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type EqualsCondition struct {
	Attribute types.String   `tfsdk:"attribute"`
	Operation types.String   `tfsdk:"operation"`
	Values    []types.String `tfsdk:"values"`
}
