// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Four struct {
	ExpiresAt      types.String `tfsdk:"expires_at"`
	Grants         []Grant      `tfsdk:"grants"`
	ID             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	OrganizationID types.String `tfsdk:"organization_id"`
	PartnerOrgID   types.String `tfsdk:"partner_org_id"`
	Slug           types.String `tfsdk:"slug"`
	Type           types.String `tfsdk:"type"`
}
