// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type GrantCondition struct {
	EqualsCondition *EqualsCondition `queryParam:"inline" tfsdk:"equals_condition" tfPlanOnly:"true"`
}
