// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type GrantCondition struct {
	EqualsCondition            *EqualsCondition            `queryParam:"inline" tfsdk:"equals_condition"`
	EqualsCurrentUserCondition *EqualsCurrentUserCondition `queryParam:"inline" tfsdk:"equals_current_user_condition"`
}
