// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type One struct {
	ExpiresAt      types.String `tfsdk:"expires_at"`
	Grants         []Grant      `tfsdk:"grants"`
	ID             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	OrganizationID types.String `tfsdk:"organization_id"`
	ParentRole     types.String `tfsdk:"parent_role"`
	Slug           types.String `tfsdk:"slug"`
	Type           types.String `tfsdk:"type"`
	VendorCreated  types.Bool   `tfsdk:"vendor_created"`
}
